In [1]:
#21BEI0107
#Sutam Chandra
#Task 1
import pandas as pd
import numpy as np


data = np.random.rand(4, 4)  # 4 features and 4 observations

# Create a DataFrame
df = pd.DataFrame(data, columns=['Feature1', 'Feature2', 'Feature3', 'Feature4'])
df

   Feature1  Feature2  Feature3  Feature4
0  0.618248  0.150551  0.363752  0.512750
1  0.306089  0.804724  0.058295  0.173491
2  0.928202  0.960446  0.332319  0.273051
3  0.981702  0.315307  0.130160  0.890628

In [2]:
#21BEI0107
#Sutam Chandra
#Task 2
#Renaming the columns
df.columns=['Random value 1','Random value 2','Random value 3','Random value 4']
df

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.618248        0.150551        0.363752        0.512750
1        0.306089        0.804724        0.058295        0.173491
2        0.928202        0.960446        0.332319        0.273051
3        0.981702        0.315307        0.130160        0.890628

In [3]:
#21BEI0107
#Sutam Chandra
#Task 3
#Descriptive statistics
df.describe()

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.708560        0.557757        0.221131        0.462480
std          0.312511        0.386329        0.149994        0.318975
min          0.306089        0.150551        0.058295        0.173491
25%          0.540208        0.274118        0.112193        0.248161
50%          0.773225        0.560016        0.231239        0.392900
75%          0.941577        0.843654        0.340177        0.607219
max          0.981702        0.960446        0.363752        0.890628

In [4]:
#21BEI0107
#Sutam Chandra
#Task 4
#Check for null values
df.isnull().sum()

Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64

In [5]:
df.dtypes
#Datatypes of columns

Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object

In [6]:
#21BEI0107
#Sutam Chandra
#Task 5
df.loc[:,'Random value 2']
#Display random value 2

0    0.150551
1    0.804724
2    0.960446
3    0.315307
Name: Random value 2, dtype: float64

In [7]:
df

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.618248        0.150551        0.363752        0.512750
1        0.306089        0.804724        0.058295        0.173491
2        0.928202        0.960446        0.332319        0.273051
3        0.981702        0.315307        0.130160        0.890628

In [8]:
df.loc[:,'Random value 3']
#Display random value 3

0    0.363752
1    0.058295
2    0.332319
3    0.130160
Name: Random value 3, dtype: float64

In [9]:
#Display random vaue 2 columns with index location method
df.iloc[:,1]

0    0.150551
1    0.804724
2    0.960446
3    0.315307
Name: Random value 2, dtype: float64

In [10]:
df.iloc[:,2]
#Display random value 3 columns with index location method

0    0.363752
1    0.058295
2    0.332319
3    0.130160
Name: Random value 3, dtype: float64